In [1]:
var = "Eu vou aprender a programar"

In [2]:
for palavras in var:
    print(palavras)

E
u
 
v
o
u
 
a
p
r
e
n
d
e
r
 
a
 
p
r
o
g
r
a
m
a
r


In [3]:
for palavras in var:
    print(palavras)
print("acabou")

E
u
 
v
o
u
 
a
p
r
e
n
d
e
r
 
a
 
p
r
o
g
r
a
m
a
r
acabou


In [6]:
var = ["Eu", "vou", "aprender", "a", "programar."]

In [9]:
for palavras in var:
    print (palavras)
print ('BEENDET')

Eu
vou
aprender
a
programar.
BEENDET


In [10]:
diasMes = list(range(1,31))

In [11]:
print(diasMes)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [12]:
for dias in diasMes:
    if dias >= 15:
        print ("já passou do dia 15. Hoje é dia: ", dias)

já passou do dia 15. Hoje é dia:  15
já passou do dia 15. Hoje é dia:  16
já passou do dia 15. Hoje é dia:  17
já passou do dia 15. Hoje é dia:  18
já passou do dia 15. Hoje é dia:  19
já passou do dia 15. Hoje é dia:  20
já passou do dia 15. Hoje é dia:  21
já passou do dia 15. Hoje é dia:  22
já passou do dia 15. Hoje é dia:  23
já passou do dia 15. Hoje é dia:  24
já passou do dia 15. Hoje é dia:  25
já passou do dia 15. Hoje é dia:  26
já passou do dia 15. Hoje é dia:  27
já passou do dia 15. Hoje é dia:  28
já passou do dia 15. Hoje é dia:  29
já passou do dia 15. Hoje é dia:  30


In [13]:
import numpy as np

In [15]:
mLoop = np.array([[11,12,13],[14,15,16],[17,18,19]])
mLoop

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
mLoop.shape[1]

3

In [20]:
for i in list(range(0,mLoop.shape[0])):
    for j in list(range(0,mLoop.shape[1])):
        print(mLoop[i,j])

11
12
13
14
15
16
17
18
19


In [26]:

anos = np.zeros((5,8))
anos

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
inicio = 2010
for i in list(range(0,anos.shape[0])):
    for j in list(range(0,anos.shape[1])):
        anos[i,j] = inicio
        inicio = inicio +1

In [29]:
anos

array([[2010., 2011., 2012., 2013., 2014., 2015., 2016., 2017.],
       [2018., 2019., 2020., 2021., 2022., 2023., 2024., 2025.],
       [2026., 2027., 2028., 2029., 2030., 2031., 2032., 2033.],
       [2034., 2035., 2036., 2037., 2038., 2039., 2040., 2041.],
       [2042., 2043., 2044., 2045., 2046., 2047., 2048., 2049.]])

In [37]:
elementos = 20
fibonacci = np.zeros(elementos)
fibonacci[1]=1

for i in list(range(2,elementos)):
    fibonacci[i] = fibonacci[i-1]+fibonacci[i-2]
    print(int(fibonacci[i]))

1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
