In [6]:
dicaInvest = "Invista 30% do seu salário 54545454"

In [2]:
dicaInvest

'Invista 30% do seu salário'

In [3]:
type(dicaInvest)

str

In [8]:
len(dicaInvest)

35

In [7]:
len(dicaInvest.split())

6

In [9]:
dicaInvest.split()

['Invista', '30%', 'do', 'seu', 'salário', '54545454']

In [12]:
str1 = "Oi" + " eu" + " sou" + " Dalton"

In [13]:
str1

'Oi eu sou Dalton'

In [14]:
print(str1.upper())

OI EU SOU DALTON


In [15]:
print(str1.lower())

oi eu sou dalton


In [16]:
str1[3:7]

'eu s'

In [17]:
str1[3:34]

'eu sou Dalton'

In [18]:
str1[6:17]

'sou Dalton'

In [19]:
import os
os.getcwd()

'C:\\Users\\dalto\\OpM na Prática'

In [20]:
os.chdir("C:\\Users\\dalto\\OpM na Prática\\Python\\Base de Dados")

In [21]:
os.getcwd()

'C:\\Users\\dalto\\OpM na Prática\\Python\\Base de Dados'

In [22]:
import csv

with open('eurusd_h1.csv') as csv_file:
    base_de_dados = csv.reader(csv_file, delimiter=';')
    for row in base_de_dados:
        print(row)

['Date', 'Open', 'High', 'Low', 'Close']
['01/01/2015 00:00', '1.20969', '1.20976', '1.20969', '1.20976']
['02/01/2015 00:00', '1.21038', '1.21073', '1.20999', '1.21014']
['02/01/2015 01:00', '1.21015', '1.2102', '1.20783', '1.20869']
['02/01/2015 02:00', '1.20871', '1.2089', '1.20668', '1.20674']
['02/01/2015 03:00', '1.20675', '1.20723', '1.20519', '1.2067']
['02/01/2015 04:00', '1.2067', '1.20687', '1.20476', '1.20588']
['02/01/2015 05:00', '1.20586', '1.20627', '1.20552', '1.20574']
['02/01/2015 06:00', '1.20574', '1.20597', '1.20492', '1.20529']
['02/01/2015 07:00', '1.20529', '1.20555', '1.20461', '1.20517']
['02/01/2015 08:00', '1.20517', '1.20577', '1.20485', '1.20546']
['02/01/2015 09:00', '1.20545', '1.20582', '1.20349', '1.20561']
['02/01/2015 10:00', '1.20564', '1.20697', '1.2045', '1.20472']
['02/01/2015 11:00', '1.20473', '1.20607', '1.2039', '1.20582']
['02/01/2015 12:00', '1.20579', '1.20581', '1.20423', '1.20509']
['02/01/2015 13:00', '1.2051', '1.20583', '1.20449', '1

['21/01/2015 07:00', '1.15658', '1.15758', '1.15612', '1.15747']
['21/01/2015 08:00', '1.15747', '1.15884', '1.15741', '1.15812']
['21/01/2015 09:00', '1.15812', '1.15848', '1.15541', '1.1557']
['21/01/2015 10:00', '1.15571', '1.15763', '1.1547', '1.15723']
['21/01/2015 11:00', '1.15722', '1.15857', '1.15645', '1.15706']
['21/01/2015 12:00', '1.15706', '1.15828', '1.1565', '1.15713']
['21/01/2015 13:00', '1.15713', '1.15838', '1.15665', '1.15764']
['21/01/2015 14:00', '1.15764', '1.15931', '1.15713', '1.15893']
['21/01/2015 15:00', '1.15893', '1.1637', '1.1587', '1.16326']
['21/01/2015 16:00', '1.16325', '1.16799', '1.1565', '1.16398']
['21/01/2015 17:00', '1.16397', '1.1659', '1.1581', '1.15866']
['21/01/2015 18:00', '1.15867', '1.16134', '1.15809', '1.15832']
['21/01/2015 19:00', '1.15834', '1.15846', '1.15661', '1.15741']
['21/01/2015 20:00', '1.15743', '1.15773', '1.15621', '1.15734']
['21/01/2015 21:00', '1.15734', '1.1596', '1.15734', '1.15904']
['21/01/2015 22:00', '1.15903', '1

['26/03/2015 09:00', '1.09833', '1.10155', '1.09794', '1.1013']
['26/03/2015 10:00', '1.10129', '1.10522', '1.10051', '1.10315']
['26/03/2015 11:00', '1.10316', '1.10432', '1.1025', '1.10361']
['26/03/2015 12:00', '1.10363', '1.10442', '1.10027', '1.10086']
['26/03/2015 13:00', '1.10086', '1.10109', '1.09905', '1.09937']
['26/03/2015 14:00', '1.09937', '1.1022', '1.09614', '1.09837']
['26/03/2015 15:00', '1.09837', '1.099', '1.09392', '1.09592']
['26/03/2015 16:00', '1.09593', '1.09606', '1.0906', '1.09183']
['26/03/2015 17:00', '1.09186', '1.09445', '1.0917', '1.09182']
['26/03/2015 18:00', '1.09182', '1.09271', '1.0906', '1.0921']
['26/03/2015 19:00', '1.09208', '1.09221', '1.08564', '1.08664']
['26/03/2015 20:00', '1.08662', '1.08825', '1.08643', '1.08708']
['26/03/2015 21:00', '1.08707', '1.08894', '1.08682', '1.0886']
['26/03/2015 22:00', '1.0886', '1.08922', '1.08766', '1.08837']
['26/03/2015 23:00', '1.08837', '1.08837', '1.08648', '1.08745']
['27/03/2015 00:00', '1.08745', '1.0

['16/04/2015 04:00', '1.07152', '1.07155', '1.06935', '1.06962']
['16/04/2015 05:00', '1.06961', '1.07093', '1.06946', '1.06981']
['16/04/2015 06:00', '1.06982', '1.07047', '1.06842', '1.0692']
['16/04/2015 07:00', '1.0692', '1.0692', '1.06752', '1.06781']
['16/04/2015 08:00', '1.06781', '1.06949', '1.0655', '1.06661']
['16/04/2015 09:00', '1.06659', '1.06852', '1.06265', '1.06383']
['16/04/2015 10:00', '1.06383', '1.06497', '1.06262', '1.06316']
['16/04/2015 11:00', '1.06315', '1.06745', '1.06247', '1.06723']
['16/04/2015 12:00', '1.06723', '1.07297', '1.06667', '1.07128']
['16/04/2015 13:00', '1.07126', '1.07468', '1.07122', '1.07297']
['16/04/2015 14:00', '1.07298', '1.07675', '1.07066', '1.07411']
['16/04/2015 15:00', '1.07409', '1.07527', '1.0722', '1.07312']
['16/04/2015 16:00', '1.07293', '1.07298', '1.06845', '1.07003']
['16/04/2015 17:00', '1.07004', '1.07428', '1.06977', '1.0742']
['16/04/2015 18:00', '1.0742', '1.07464', '1.07243', '1.07302']
['16/04/2015 19:00', '1.07305', 

['20/07/2015 04:00', '1.08224', '1.08299', '1.08207', '1.08239']
['20/07/2015 05:00', '1.08241', '1.08252', '1.08204', '1.08216']
['20/07/2015 06:00', '1.08216', '1.08297', '1.08213', '1.08294']
['20/07/2015 07:00', '1.08294', '1.08298', '1.0824', '1.08291']
['20/07/2015 08:00', '1.08291', '1.08482', '1.08247', '1.08415']
['20/07/2015 09:00', '1.08414', '1.08646', '1.0841', '1.08621']
['20/07/2015 10:00', '1.08622', '1.08631', '1.0844', '1.08493']
['20/07/2015 11:00', '1.08495', '1.08572', '1.08254', '1.08373']
['20/07/2015 12:00', '1.08375', '1.08407', '1.08282', '1.08384']
['20/07/2015 13:00', '1.08384', '1.08475', '1.08335', '1.08464']
['20/07/2015 14:00', '1.08464', '1.08591', '1.08413', '1.08463']
['20/07/2015 15:00', '1.08462', '1.08495', '1.0831', '1.08343']
['20/07/2015 16:00', '1.08344', '1.08665', '1.08344', '1.08639']
['20/07/2015 17:00', '1.08645', '1.08702', '1.08472', '1.08493']
['20/07/2015 18:00', '1.08493', '1.0857', '1.084', '1.08411']
['20/07/2015 19:00', '1.08411', 

['16/11/2015 11:00', '1.07386', '1.07396', '1.07156', '1.07262']
['16/11/2015 12:00', '1.07264', '1.07313', '1.07137', '1.07205']
['16/11/2015 13:00', '1.07205', '1.07454', '1.07204', '1.07386']
['16/11/2015 14:00', '1.07387', '1.07419', '1.0724', '1.07302']
['16/11/2015 15:00', '1.07305', '1.07416', '1.07224', '1.07281']
['16/11/2015 16:00', '1.07281', '1.07306', '1.07035', '1.07041']
['16/11/2015 17:00', '1.07043', '1.07194', '1.07011', '1.07164']
['16/11/2015 18:00', '1.07167', '1.07237', '1.0706', '1.07073']
['16/11/2015 19:00', '1.07074', '1.07094', '1.06913', '1.06938']
['16/11/2015 20:00', '1.06937', '1.06986', '1.06822', '1.06865']
['16/11/2015 21:00', '1.06864', '1.06931', '1.06745', '1.06771']
['16/11/2015 22:00', '1.06772', '1.06874', '1.06762', '1.0685']
['16/11/2015 23:00', '1.0685', '1.06888', '1.06824', '1.06858']
['17/11/2015 00:00', '1.06862', '1.06867', '1.06813', '1.06832']
['17/11/2015 01:00', '1.0683', '1.06892', '1.0683', '1.06871']
['17/11/2015 02:00', '1.06873',

['14/03/2016 18:00', '1.11063', '1.11221', '1.10996', '1.11002']
['14/03/2016 19:00', '1.11002', '1.11074', '1.10839', '1.10851']
['14/03/2016 20:00', '1.10853', '1.10939', '1.10779', '1.10934']
['14/03/2016 21:00', '1.10938', '1.10992', '1.10933', '1.10975']
['14/03/2016 22:00', '1.10976', '1.11069', '1.10975', '1.11018']
['14/03/2016 23:00', '1.11009', '1.11029', '1.10993', '1.11014']
['15/03/2016 00:00', '1.11014', '1.11081', '1.10999', '1.11031']
['15/03/2016 01:00', '1.11033', '1.11038', '1.10995', '1.10999']
['15/03/2016 02:00', '1.11', '1.11011', '1.10938', '1.10992']
['15/03/2016 03:00', '1.10991', '1.11092', '1.10985', '1.11089']
['15/03/2016 04:00', '1.11089', '1.11153', '1.11067', '1.11104']
['15/03/2016 05:00', '1.11102', '1.11128', '1.11014', '1.11099']
['15/03/2016 06:00', '1.11099', '1.11116', '1.11066', '1.11072']
['15/03/2016 07:00', '1.11071', '1.11085', '1.11001', '1.11063']
['15/03/2016 08:00', '1.11063', '1.11072', '1.11018', '1.11061']
['15/03/2016 09:00', '1.1106

['18/07/2016 06:00', '1.10641', '1.10664', '1.10617', '1.10654']
['18/07/2016 07:00', '1.10653', '1.107', '1.10628', '1.10685']
['18/07/2016 08:00', '1.10685', '1.10726', '1.10512', '1.10575']
['18/07/2016 09:00', '1.10576', '1.10628', '1.10464', '1.10517']
['18/07/2016 10:00', '1.10518', '1.10613', '1.10487', '1.1051']
['18/07/2016 11:00', '1.10511', '1.10577', '1.10376', '1.10428']
['18/07/2016 12:00', '1.10429', '1.10505', '1.1038', '1.10495']
['18/07/2016 13:00', '1.10496', '1.10593', '1.10478', '1.10573']
['18/07/2016 14:00', '1.10574', '1.10598', '1.10473', '1.10512']
['18/07/2016 15:00', '1.10513', '1.10649', '1.10481', '1.10646']
['18/07/2016 16:00', '1.10645', '1.10696', '1.10582', '1.10668']
['18/07/2016 17:00', '1.10667', '1.10842', '1.10612', '1.10754']
['18/07/2016 18:00', '1.10755', '1.10823', '1.10637', '1.10712']
['18/07/2016 19:00', '1.10713', '1.1082', '1.10695', '1.10749']
['18/07/2016 20:00', '1.1075', '1.10768', '1.1068', '1.10688']
['18/07/2016 21:00', '1.10689', 

['11/11/2016 17:00', '1.08772', '1.08788', '1.08502', '1.08507']
['11/11/2016 18:00', '1.08509', '1.0862', '1.08303', '1.0834']
['11/11/2016 19:00', '1.08341', '1.08638', '1.08323', '1.08597']
['11/11/2016 20:00', '1.08596', '1.086', '1.08459', '1.08466']
['11/11/2016 21:00', '1.08465', '1.085', '1.08413', '1.08444']
['11/11/2016 22:00', '1.08441', '1.08507', '1.08441', '1.0847']
['11/11/2016 23:00', '1.08471', '1.0861', '1.08461', '1.08516']
['14/11/2016 00:00', '1.0833', '1.08401', '1.08311', '1.08384']
['14/11/2016 01:00', '1.08382', '1.08396', '1.08191', '1.08226']
['14/11/2016 02:00', '1.08226', '1.08258', '1.0794', '1.08065']
['14/11/2016 03:00', '1.08066', '1.08081', '1.07728', '1.07964']
['14/11/2016 04:00', '1.07965', '1.08071', '1.0789', '1.08049']
['14/11/2016 05:00', '1.08049', '1.08087', '1.0796', '1.07977']
['14/11/2016 06:00', '1.07978', '1.0801', '1.07948', '1.07974']
['14/11/2016 07:00', '1.07977', '1.07985', '1.07783', '1.0792']
['14/11/2016 08:00', '1.0792', '1.07997

['13/03/2017 09:00', '1.07121', '1.07142', '1.0694', '1.06956']
['13/03/2017 10:00', '1.06955', '1.06972', '1.06712', '1.0674']
['13/03/2017 11:00', '1.06744', '1.06786', '1.06647', '1.0665']
['13/03/2017 12:00', '1.06651', '1.06745', '1.06631', '1.06733']
['13/03/2017 13:00', '1.06732', '1.06768', '1.06672', '1.06676']
['13/03/2017 14:00', '1.06677', '1.06757', '1.06589', '1.06591']
['13/03/2017 15:00', '1.06591', '1.06704', '1.06559', '1.06703']
['13/03/2017 16:00', '1.06704', '1.06716', '1.06557', '1.06658']
['13/03/2017 17:00', '1.06659', '1.06791', '1.0664', '1.06692']
['13/03/2017 18:00', '1.06692', '1.06732', '1.06617', '1.06624']
['13/03/2017 19:00', '1.06624', '1.06659', '1.06558', '1.06589']
['13/03/2017 20:00', '1.06589', '1.06611', '1.06532', '1.06599']
['13/03/2017 21:00', '1.06601', '1.06604', '1.06534', '1.0654']
['13/03/2017 22:00', '1.06538', '1.06548', '1.0652', '1.06536']
['13/03/2017 23:00', '1.06531', '1.0655', '1.06523', '1.06538']
['14/03/2017 00:00', '1.06536', 

['13/07/2017 09:00', '1.14467', '1.14528', '1.1413', '1.14215']
['13/07/2017 10:00', '1.14214', '1.14229', '1.13956', '1.14035']
['13/07/2017 11:00', '1.14034', '1.14081', '1.13856', '1.13959']
['13/07/2017 12:00', '1.13962', '1.14054', '1.13759', '1.13881']
['13/07/2017 13:00', '1.13882', '1.14128', '1.13705', '1.14107']
['13/07/2017 14:00', '1.14104', '1.14191', '1.14021', '1.14162']
['13/07/2017 15:00', '1.14161', '1.14177', '1.13983', '1.13987']
['13/07/2017 16:00', '1.13988', '1.14148', '1.13908', '1.14037']
['13/07/2017 17:00', '1.14038', '1.14078', '1.13837', '1.13839']
['13/07/2017 18:00', '1.1384', '1.13918', '1.13826', '1.13905']
['13/07/2017 19:00', '1.13907', '1.13994', '1.13892', '1.13972']
['13/07/2017 20:00', '1.13973', '1.14062', '1.13964', '1.14042']
['13/07/2017 21:00', '1.14041', '1.14068', '1.1402', '1.14067']
['13/07/2017 22:00', '1.14067', '1.14067', '1.13958', '1.13973']
['13/07/2017 23:00', '1.13973', '1.1402', '1.13967', '1.14']
['14/07/2017 00:00', '1.13999', 

['22/11/2017 12:00', '1.17565', '1.17565', '1.17485', '1.17499']
['22/11/2017 13:00', '1.17499', '1.17546', '1.17457', '1.17528']
['22/11/2017 14:00', '1.1753', '1.1753', '1.1736', '1.17422']
['22/11/2017 15:00', '1.17419', '1.17542', '1.17403', '1.17507']
['22/11/2017 16:00', '1.17507', '1.17779', '1.175', '1.17758']
['22/11/2017 17:00', '1.17758', '1.17969', '1.17714', '1.17859']
['22/11/2017 18:00', '1.17861', '1.17979', '1.17834', '1.17886']
['22/11/2017 19:00', '1.17886', '1.17984', '1.1786', '1.17951']
['22/11/2017 20:00', '1.17952', '1.17989', '1.17925', '1.17984']
['22/11/2017 21:00', '1.17982', '1.18269', '1.17951', '1.18247']
['22/11/2017 22:00', '1.18252', '1.18252', '1.18137', '1.18201']
['22/11/2017 23:00', '1.18199', '1.18249', '1.18182', '1.18215']
['23/11/2017 00:00', '1.18214', '1.18223', '1.18165', '1.18183']
['23/11/2017 01:00', '1.18183', '1.18216', '1.18136', '1.18146']
['23/11/2017 02:00', '1.18147', '1.18203', '1.18132', '1.18141']
['23/11/2017 03:00', '1.18141',

['17/04/2018 04:00', '1.23807', '1.23812', '1.23757', '1.23811']
['17/04/2018 05:00', '1.23811', '1.2384', '1.23785', '1.23811']
['17/04/2018 06:00', '1.23812', '1.23863', '1.23807', '1.23822']
['17/04/2018 07:00', '1.23822', '1.23889', '1.23816', '1.23884']
['17/04/2018 08:00', '1.23883', '1.24046', '1.23856', '1.24016']
['17/04/2018 09:00', '1.24016', '1.24136', '1.23951', '1.2402']
['17/04/2018 10:00', '1.24022', '1.24029', '1.23844', '1.23853']
['17/04/2018 11:00', '1.23855', '1.23869', '1.23648', '1.2372']
['17/04/2018 12:00', '1.23722', '1.23737', '1.23618', '1.23714']
['17/04/2018 13:00', '1.23713', '1.23804', '1.23666', '1.23672']
['17/04/2018 14:00', '1.23673', '1.23676', '1.23452', '1.23477']
['17/04/2018 15:00', '1.23476', '1.23613', '1.23458', '1.23514']
['17/04/2018 16:00', '1.23513', '1.23543', '1.23362', '1.23459']
['17/04/2018 17:00', '1.23462', '1.23492', '1.23364', '1.23447']
['17/04/2018 18:00', '1.23447', '1.2357', '1.23379', '1.2355']
['17/04/2018 19:00', '1.23551'

In [23]:
import pandas as pd

In [24]:
base_de_dados = pd.read_csv("eurusd_h1.csv", delimiter=";")

In [25]:
type(base_de_dados)

pandas.core.frame.DataFrame

In [26]:
base_de_dados.head()

Date     Open     High      Low    Close
0  01/01/2015 00:00  1.20969  1.20976  1.20969  1.20976
1  02/01/2015 00:00  1.21038  1.21073  1.20999  1.21014
2  02/01/2015 01:00  1.21015  1.21020  1.20783  1.20869
3  02/01/2015 02:00  1.20871  1.20890  1.20668  1.20674
4  02/01/2015 03:00  1.20675  1.20723  1.20519  1.20670

In [27]:
base_de_dados.shape

(22245, 5)

In [28]:
base_de_dados.dtypes

Date      object
Open     float64
High     float64
Low      float64
Close    float64
dtype: object

In [29]:
base_de_dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22245 entries, 0 to 22244
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    22245 non-null  object 
 1   Open    22245 non-null  float64
 2   High    22245 non-null  float64
 3   Low     22245 non-null  float64
 4   Close   22245 non-null  float64
dtypes: float64(4), object(1)
memory usage: 869.1+ KB


In [32]:
baseDeDados2 = pd.read_table("eurusd_h1.txt", delimiter = "|")

In [33]:
baseDeDados2.head()

Date     Open     High      Low    Close
0  01/01/2015 00:00  1.20969  1.20976  1.20969  1.20976
1  02/01/2015 00:00  1.21038  1.21073  1.20999  1.21014
2  02/01/2015 01:00  1.21015  1.21020  1.20783  1.20869
3  02/01/2015 02:00  1.20871  1.20890  1.20668  1.20674
4  02/01/2015 03:00  1.20675  1.20723  1.20519  1.20670

In [35]:
baseDeDados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22245 entries, 0 to 22244
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    22245 non-null  object 
 1   Open    22245 non-null  float64
 2   High    22245 non-null  float64
 3   Low     22245 non-null  float64
 4   Close   22245 non-null  float64
dtypes: float64(4), object(1)
memory usage: 869.1+ KB


In [36]:
#MATRIZES

In [37]:
matriz1 = [[10,11,12],[13,14,15]]

In [38]:
matriz1

[[10, 11, 12], [13, 14, 15]]

In [39]:
len(matriz1)

2

In [40]:
import numpy as np

In [44]:
matriz2 = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [45]:
matriz2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [46]:
matriz2.shape

(3, 3)

In [47]:
type(matriz2)

numpy.ndarray

In [49]:
matriz2[:,1]

array([11, 14, 17])

In [50]:
from numpy import *

In [51]:
matriz2 = append(matriz2, [[19,20,21]],0)

In [52]:
matriz2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [59]:
matriz2 = insert(matriz2, [3],[[1],[2],[3],[4]],1)
matriz2

array([[10, 11, 12,  1,  1,  1,  1],
       [13, 14, 15,  2,  2,  2,  2],
       [16, 17, 18,  3,  3,  3,  3],
       [19, 20, 21,  4,  4,  4,  4]])

matriz2

In [60]:
matriz2

array([[10, 11, 12,  1,  1,  1,  1],
       [13, 14, 15,  2,  2,  2,  2],
       [16, 17, 18,  3,  3,  3,  3],
       [19, 20, 21,  4,  4,  4,  4]])

In [62]:
zeros = np.zeros((5,4))

In [63]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])