In [1]:
def somaQuadrados (a,b):
    return a*a+b*b

In [3]:
somaQuadrados(2,7)

53

In [4]:
import datetime

In [5]:
def diaDeHoje():
    print("Hoje é "+ str(datetime.datetime.now()))

In [14]:
diaDeHoje("No Brasil é ")

No Brasil é 2021-08-02 18:16:39.676283


In [13]:
def diaDeHoje(txt = "Hoje ée "):
    print(txt+ str(datetime.datetime.now()))

In [15]:
import numpy as np

In [19]:
def fibo(elementos):
    fibonacci = np.zeros(elementos)
    fibonacci[1]=1
    for i in list(range(2,elementos)):
        fibonacci[i] = fibonacci[i-1]+fibonacci[i-2]
    print(fibonacci)

In [23]:
fibo(12)

[ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34. 55. 89.]


In [34]:
def minhaRNA (inputs, outputs, iteracoes):
    w1 = 2*np.random.random((inputs.shape[1], inputs.shape[0])) - 1
    w2 = 2*np.random.random((outputs.shape[0], outputs.shape[1])) - 1

    for iteracao in range (iteracoes):
        camada1 = 1 / (1 + np.exp(-(np.dot(inputs,w1))))
        camada2 = 1 / (1 + np.exp(-(np.dot(camada1,w2)))) 
        camada2_delta = (outputs - camada2) * (camada2*(1-camada2))
        camada1_delta = camada2_delta.dot(w2.T) * (camada1 * (1 - camada1))
        w2 += camada1.T.dot(camada2_delta)
        w1 += inputs.T.dot(camada1_delta)
    print(camada2)

In [27]:
entradas = np.array([[0,0], [0,1], [1,0], [1,1]])
saidas = np.array([[0,0,0,1]]).T

In [30]:
minhaRNA(entradas,saidas,10000)

[[0.]
 [0.]
 [0.]
 [1.]]


In [31]:
in_or = np.array([[0,0], [0,1], [1,0], [1,1]])
out_or = np.array([[0,1,1,1]]).T

In [32]:
minhaRNA(in_or,out_or,10000)

[[0.]
 [1.]
 [1.]
 [1.]]


In [39]:
out_xor = np.array([[0,1,1,0]]).T
minhaRNA(in_or,out_xor,100000)

[[0.00409383]
 [0.99523417]
 [0.99522289]
 [0.00488952]]


In [40]:
import pandas as pd

In [43]:
v1 = [1958,1962,1970,1994,2002]
v2 = [1,1,2,3,5]
v3 = [10,100,1000,5,25]

df = pd.DataFrame({'v1' : v1, 'v2' : v2, 'v3' : v3})

df

v1  v2    v3
0  1958   1    10
1  1962   1   100
2  1970   2  1000
3  1994   3     5
4  2002   5    25

In [49]:
df[["v1","v3","v2"]]

v1    v3  v2
0  1958    10   1
1  1962   100   1
2  1970  1000   2
3  1994     5   3
4  2002    25   5

In [46]:
df.iloc[1]

v1    1962
v2       1
v3     100
Name: 1, dtype: int64

In [52]:
import os
os.chdir("C:\\Users\\dalto\\OpM na Prática\\Python\\Base de Dados")

mtcars = pd.read_csv("mtcars.csv", delimiter = ";")

In [53]:
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [54]:
mtcars.tail()

mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [55]:
list(mtcars)

['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

In [56]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64  
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64  
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64  
 8   am      32 non-null     int64  
 9   gear    32 non-null     int64  
 10  carb    32 non-null     int64  
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB


In [57]:
mtcars.shape

(32, 11)

In [58]:
subset = mtcars[["mpg", "cyl"]]

In [59]:
subset.head()

mpg  cyl
Mazda RX4          21.0    6
Mazda RX4 Wag      21.0    6
Datsun 710         22.8    4
Hornet 4 Drive     21.4    6
Hornet Sportabout  18.7    8

In [60]:
subset_rows = mtcars.loc[['Hornet Sportabout', 'Merc 240D']]
subset_rows.head()

mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  \
Hornet Sportabout  18.7    8  360.0  175  3.15  3.44  17.02   0   0     3   
Merc 240D          24.4    4  146.7   62  3.69  3.19  20.00   1   0     4   

                   carb  
Hornet Sportabout     2  
Merc 240D             2

In [63]:
subset2 = mtcars.loc[['Hornet Sportabout', 'Merc 240D',"Ferrari Dino", "Ford Pantera L"],["mpg","hp"]]
subset2.head()

mpg   hp
Hornet Sportabout  18.7  175
Merc 240D          24.4   62
Ferrari Dino       19.7  175
Ford Pantera L     15.8  264