In [1]:
#Rede Neural mais simples que existe é o Perceptron

In [3]:
import random
random.seed(1)

In [4]:
import numpy as np

In [5]:
entradas = np.array([[0,0],[0,1],[1,0],[1,1]])
saidas = np.array([[0,0,0,1]]).T

In [6]:
entradas

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [7]:
saidas

array([[0],
       [0],
       [0],
       [1]])

In [8]:
w1 = 2*np.random.random((2,4)) - 1
w2 = 2*np.random.random((4,1)) - 1

In [9]:
w1

array([[ 0.6905939 , -0.97631101, -0.54660904, -0.81382297],
       [-0.7961058 , -0.72731301,  0.26359352,  0.41774156]])

In [10]:
w2

array([[ 0.42909253],
       [ 0.40699389],
       [-0.82384511],
       [ 0.7331564 ]])

In [11]:
#treinamento da rede neural

for iteracao in range (1000000):
    camada1 = 1 / (1 + np.exp(-(np.dot(entradas,w1))))
    camada2 = 1 / (1 + np.exp(-(np.dot(camada1,w2)))) 
    camada2_delta = (saidas - camada2) * (camada2*(1-camada2))
    camada1_delta = camada2_delta.dot(w2.T) * (camada1 * (1 - camada1))
    w2 += camada1.T.dot(camada2_delta)
    w1 += entradas.T.dot(camada1_delta)

In [17]:
camada2

array([[1.10085861e-04],
       [7.11351919e-04],
       [7.38064570e-04],
       [9.98962872e-01]])

In [13]:
camada2.round()

array([[0.],
       [0.],
       [0.],
       [1.]])